hydra:
  launcher:
    _target_: hydra_plugins.hydra_joblib_launcher.JoblibLauncher
    n_jobs: 10
    backend: loky
    verbosity: 0

srun --cpus-per-task=8 -J NeurIPS -p cpu-research  -q research --pty python run.py --config-name=deadline -m ++num_seeds=3 ++H=8000,14000
srun --cpus-per-task=8 -J NeurIPS -p cpu-research  -q research --pty python run.py --config-name=toy -m ++num_seeds=3 ++H=2000
srun --cpus-per-task=8 -J NeurIPS -p cpu-research  -q research --pty python run.py --config-name=vs -m ++num_seeds=3 ++H=4000,10000
srun --cpus-per-task=8 -J NeurIPS -p cpu-research  -q research --pty python run.py --config-name=wireless -m ++num_seeds=3 ++H=5000,13000
srun --cpus-per-task=8 -J NeurIPS -p cpu-research  -q research --pty python run.py --config-name=cpap -m ++num_seeds=3 ++H=8000,13000


toy_env_H_300_eps_1e-10_seed_1	10000
wireless_raju_seed_1	10000
deadline_env_H_40_eps_1e-10_seed_1	10000
cpap_env_H_300_eps_1e-05_seed_1	10000
wireless_env_H_40_eps_1e-05_seed_1	10000
cpap_env_H_100_eps_1e-05_seed_1	10000
vs_env_H_40_eps_1e-10_seed_1	1183
vs_env_H_40_eps_1e-05_seed_1	765
vs_env_H_300_eps_1e-10_seed_1	491
vs_env_H_300_eps_1e-05_seed_1	350